language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
before_install:
  - composer self-update
install:
  - composer install --no-interaction --prefer-source
script:
  - vendor/bin/phpunit
notifications:
  email: false
